// Renders PROJECT_STATUS.md from the database. The file is a snapshot for reading in the repo and
// on GitHub: nothing reads it back, so edits made in it are overwritten by the next export.
// Projects are edited in the dashboard's Projects tab. The output depends only on the database
// (no dates, no clock), so `cc export --check` can tell whether the file is current.

import type { Project, Store, Task } from '../core/index.ts';

export const GENERATED_COMMENT =
  '<!-- Generated by command-center export (npm run cc -- export). Do not edit: the next export overwrites this file. Edit projects and tasks in the dashboard. -->\n';

const INTRO = '# Project Status\n\n*A snapshot of the Command Center. Run `npm run cc -- export` to refresh it.*\n';

/** Checkbox lines for a list of tasks. A task's notes are indented one step under its checkbox. */
export function renderChecklist(items: { text: string; checked: boolean; notes?: string; depth?: number }[]): string {
  return items.map((it) => {
    const pad = '  '.repeat(it.depth ?? 0);
    const line = `${pad}- [${it.checked ? 'x' : ' '}] ${it.text}`;
    const notes = (it.notes ?? '').trim();
    if (!notes) return line;
    const body = notes.split('\n').map((l) => (l.trim() ? `${pad}  ${l}` : '')).join('\n');
    return `${line}\n${body}`;
  }).join('\n');
}

/**
 * The tasks listed under a project: what the owner has not finished, written by them or for them, with
 * subtasks under their parent. Third-party text never goes into this file, so a task that carries
 * untrusted text is left out, and so is anything that came from an external source or from a
 * checklist that lives in the project's own repo.
 */
function nextStepsTasksFor(store: Store, projectId: string): { task: Task; depth: number }[] {
  const all = store.searchAllTasks({ projectId, orderBy: 'position' })
    .filter((t) => ['open', 'in_progress', 'waiting'].includes(t.status))
    .filter((t) => !t.untrustedText && (t.sourceType === null || t.sourceType === 'status_md'));
  const ids = new Set(all.map((t) => t.id));
  const byParent = new Map<string | null, Task[]>();
  for (const t of all) {
    // A subtask whose parent is not listed (done, or left out above) is shown at the top level.
    const parent = t.parentId && ids.has(t.parentId) ? t.parentId : null;
    if (!byParent.has(parent)) byParent.set(parent, []);
    byParent.get(parent)!.push(t);
  }
  const out: { task: Task; depth: number }[] = [];
  const walk = (task: Task, depth: number): void => {
    out.push({ task, depth });
    for (const child of byParent.get(task.id) ?? []) walk(child, depth + 1);
  };
  for (const t of byParent.get(null) ?? []) walk(t, 0);
  return out;
}

function renderProject(store: Store, project: Project): string {
  const fields = [
    project.type ? `**Type:** ${project.type}` : '',
    project.status ? `**Status:** ${project.status}` : '',
    project.github ? `**GitHub:** ${project.github}` : '',
  ].filter(Boolean);
  const tasks = nextStepsTasksFor(store, project.id);
  const blocks = [
    `## ${project.name}`,
    // Two trailing spaces make a markdown line break, so the fields stack instead of running together.
    fields.join('  \n'),
    (project.description ?? '').trim(),
    tasks.length
      ? `### Next Steps\n${renderChecklist(tasks.map(({ task, depth }) => ({ text: task.title, checked: false, notes: task.notes, depth })))}`
      : '',
  ].filter(Boolean);
  return blocks.join('\n\n');
}

export function renderStatusDoc(store: Store): string {
  // Initiatives have their own files in initiatives/. Archived projects are left out. Lowercased
  // name, then slug, compared by code unit: a total order that does not depend on the ICU data
  // Node was built with, so the same database always writes the same file.
  const cmp = (x: string, y: string): number => (x < y ? -1 : x > y ? 1 : 0);
  const projects = store.listProjects()
    .filter((p) => p.category !== 'initiative')
    .sort((a, b) => cmp(a.name.toLowerCase(), b.name.toLowerCase()) || cmp(a.slug, b.slug));
  const sections = projects.map((p) => `\n---\n\n${renderProject(store, p)}\n`);
  return GENERATED_COMMENT + INTRO + sections.join('');
}
