import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { openApp } from '../app.ts';
import { commands } from './commands.ts';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, 'fixtures', 'full-repo');

// import/export each open and close their own connection, so cross-command tests need a
// file-backed DB (":memory:" would lose everything the moment the first command closes it).
function tempDbPath(): { dbPath: string; cleanup: () => void } {
  const dir = mkdtempSync(join(tmpdir(), 'cc-commands-'));
  return { dbPath: join(dir, 'test.db'), cleanup: () => rmSync(dir, { recursive: true, force: true }) };
}

const importCommand = commands.find((c) => c.name === 'import')!;
const exportCommand = commands.find((c) => c.name === 'export')!;

function capture() {
  const out: string[] = [];
  const err: string[] = [];
  return { out, err, stdout: (s: string) => out.push(s), stderr: (s: string) => err.push(s) };
}

test('commands: import + export --dry-run run end to end against a fixture repo', async () => {
  const { dbPath, cleanup } = tempDbPath();
  try {
    const ctxOpenApp = () => openApp({ dbPath, repoRoot });

    const io1 = capture();
    const code1 = await importCommand.run([], { openApp: ctxOpenApp, stdout: io1.stdout, stderr: io1.stderr });
    assert.equal(code1, 0);
    assert.ok(io1.out.join('\n').includes('Command Center import summary'));

    const io2 = capture();
    const code2 = await exportCommand.run(['--dry-run'], { openApp: ctxOpenApp, stdout: io2.stdout, stderr: io2.stderr });
    assert.equal(code2, 0);
    const text = io2.out.join('\n');
    assert.match(text, /PROJECT_STATUS\.md/);
    assert.match(text, /Generated by command-center export/);

    // A second import with no source changes must not blow up and should report no drift.
    const io3 = capture();
    const code3 = await importCommand.run([], { openApp: ctxOpenApp, stdout: io3.stdout, stderr: io3.stderr });
    assert.equal(code3, 0);
  } finally {
    cleanup();
  }
});

test('commands: import against a repo root with no initiatives/ says so in one line and exits 0', async () => {
  const { dbPath, cleanup } = tempDbPath();
  try {
    // The public repo, or an install, has no initiatives folder: the importer is for a repo that
    // keeps its plans as initiatives/*.md and does nothing otherwise, without throwing.
    const bareRoot = join(dirname(dbPath), 'no-initiatives-here');
    const io = capture();
    const code = await importCommand.run([], { openApp: () => openApp({ dbPath, repoRoot: bareRoot }), stdout: io.stdout, stderr: io.stderr });
    assert.equal(code, 0);
    assert.equal(io.out.length, 1);
    assert.match(io.out[0], /Nothing to import: no initiatives folder at /);
    assert.ok(io.out[0].includes(join(bareRoot, 'initiatives')));
    assert.deepEqual(io.err, []);

    const app = openApp({ dbPath, repoRoot: bareRoot });
    try {
      assert.equal(app.store.listProjects({ includeArchived: true }).length, 0);
    } finally {
      app.close();
    }
  } finally {
    cleanup();
  }
});

test('commands: export --check exits 1 when the on-disk file would differ, 0 once written', async () => {
  const { dbPath, cleanup } = tempDbPath();
  try {
    const ctxOpenApp = () => openApp({ dbPath, repoRoot });
    await importCommand.run([], { openApp: ctxOpenApp, stdout: () => {}, stderr: () => {} });

    // The fixture PROJECT_STATUS.md on disk was hand-written, not generated, so it must differ
    // (at minimum by the generated-file comment) from a fresh render.
    const io1 = capture();
    const code1 = await exportCommand.run(['--check'], { openApp: ctxOpenApp, stdout: io1.stdout, stderr: io1.stderr });
    assert.equal(code1, 1);
    assert.ok(io1.err.some((l) => l.includes('PROJECT_STATUS.md differs')));
  } finally {
    cleanup();
  }
});

